// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO-FRVMHD1LaleXLQRwuZ0bJfjkDPuUIU',
    appId: '1:741066874798:web:6d7ad9daa9d9a3f896323f',
    messagingSenderId: '741066874798',
    projectId: 'flutterex1-f7bae',
    authDomain: 'flutterex1-f7bae.firebaseapp.com',
    databaseURL:
        'https://flutterex1-f7bae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterex1-f7bae.appspot.com',
    measurementId: 'G-PGXQF6QDQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfT8_xp0UNlqpD-mIMspAqMektBENQaQk',
    appId: '1:741066874798:android:ebbeca5df285ec1b96323f',
    messagingSenderId: '741066874798',
    projectId: 'flutterex1-f7bae',
    databaseURL:
        'https://flutterex1-f7bae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterex1-f7bae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyoOGMOh86iQHQe2xWMNh9Y2yyMNxxN2Q',
    appId: '1:741066874798:ios:25fe05f1a1100bdd96323f',
    messagingSenderId: '741066874798',
    projectId: 'flutterex1-f7bae',
    databaseURL:
        'https://flutterex1-f7bae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterex1-f7bae.appspot.com',
    iosClientId:
        '741066874798-v335bovfslhoi341qtnni2qip0j0r8n2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyoOGMOh86iQHQe2xWMNh9Y2yyMNxxN2Q',
    appId: '1:741066874798:ios:25fe05f1a1100bdd96323f',
    messagingSenderId: '741066874798',
    projectId: 'flutterex1-f7bae',
    databaseURL:
        'https://flutterex1-f7bae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterex1-f7bae.appspot.com',
    iosClientId:
        '741066874798-v335bovfslhoi341qtnni2qip0j0r8n2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO-FRVMHD1LaleXLQRwuZ0bJfjkDPuUIU',
    appId: '1:741066874798:web:908b63e39e50f9be96323f',
    messagingSenderId: '741066874798',
    projectId: 'flutterex1-f7bae',
    authDomain: 'flutterex1-f7bae.firebaseapp.com',
    databaseURL:
        'https://flutterex1-f7bae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterex1-f7bae.appspot.com',
    measurementId: 'G-ZR8E2XLPBS',
  );
}
